//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OWAOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlternativaMatrizs
    {
        public AlternativaMatrizs()
        {
            this.AlternativaFilas = new HashSet<AlternativaFilas>();
        }
    
        public int AlternativaMatrizId { get; set; }
        public bool Consistencia { get; set; }
        public int CriterioId { get; set; }
        public Nullable<int> ExpertoEnProyecto_ExpertoEnProyectoId { get; set; }
        public Nullable<int> ValoracionAHP_Id { get; set; }
    
        public virtual ICollection<AlternativaFilas> AlternativaFilas { get; set; }
        public virtual Criterios Criterios { get; set; }
        public virtual ExpertosEnProyecto ExpertosEnProyecto { get; set; }
        public virtual ValoracionAHPs ValoracionAHPs { get; set; }
    }
}
