//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OWAOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alternativas
    {
        public Alternativas()
        {
            this.AlternativaCeldas = new HashSet<AlternativaCeldas>();
            this.AlternativaFilas = new HashSet<AlternativaFilas>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Proyecto_ProyectoId { get; set; }
    
        public virtual ICollection<AlternativaCeldas> AlternativaCeldas { get; set; }
        public virtual ICollection<AlternativaFilas> AlternativaFilas { get; set; }
        public virtual Proyectos Proyectos { get; set; }
    }
}
