//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OWAOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlternativaCeldas
    {
        public int AlternativaCeldaId { get; set; }
        public int Fila { get; set; }
        public int Columna { get; set; }
        public double ValorAHP { get; set; }
        public int ValorILNumerico { get; set; }
        public string ValorILLinguistico { get; set; }
        public int AlternativaId { get; set; }
        public Nullable<int> AlternativaFila_AlternativaFilaId { get; set; }
    
        public virtual AlternativaFilas AlternativaFilas { get; set; }
        public virtual Alternativas Alternativas { get; set; }
    }
}
