//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OWAOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlternativaILs
    {
        public AlternativaILs()
        {
            this.ValorCriterios = new HashSet<ValorCriterios>();
        }
    
        public int AlternativaILId { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public bool Valorada { get; set; }
        public int ValoracionIL_Id { get; set; }
    
        public virtual ValoracionILs ValoracionILs { get; set; }
        public virtual ICollection<ValorCriterios> ValorCriterios { get; set; }
    }
}
