//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OWAOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConjuntoEtiquetas
    {
        public ConjuntoEtiquetas()
        {
            this.Etiquetas = new HashSet<Etiquetas>();
            this.ValoracionILs = new HashSet<ValoracionILs>();
        }
    
        public int ConjuntoEtiquetasId { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int Cantidad { get; set; }
        public int Token { get; set; }
        public int Tipo { get; set; }
        public Nullable<int> ProyectoId { get; set; }
    
        public virtual Proyectos Proyectos { get; set; }
        public virtual ICollection<Etiquetas> Etiquetas { get; set; }
        public virtual ICollection<ValoracionILs> ValoracionILs { get; set; }
    }
}
