//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OWAOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criterios
    {
        public Criterios()
        {
            this.AlternativaMatrizs = new HashSet<AlternativaMatrizs>();
            this.CriterioCeldas = new HashSet<CriterioCeldas>();
            this.CriterioFilas = new HashSet<CriterioFilas>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Proyecto_ProyectoId { get; set; }
    
        public virtual ICollection<AlternativaMatrizs> AlternativaMatrizs { get; set; }
        public virtual ICollection<CriterioCeldas> CriterioCeldas { get; set; }
        public virtual ICollection<CriterioFilas> CriterioFilas { get; set; }
        public virtual Proyectos Proyectos { get; set; }
    }
}
