//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OWAOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriterioFilas
    {
        public CriterioFilas()
        {
            this.CriterioCeldas = new HashSet<CriterioCeldas>();
        }
    
        public int CriterioFilaId { get; set; }
        public int CriterioId { get; set; }
        public Nullable<int> CriterioMatriz_CriterioMatrizId { get; set; }
    
        public virtual ICollection<CriterioCeldas> CriterioCeldas { get; set; }
        public virtual CriterioMatrizs CriterioMatrizs { get; set; }
        public virtual Criterios Criterios { get; set; }
    }
}
