//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OWAOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriterioMatrizs
    {
        public CriterioMatrizs()
        {
            this.CriterioFilas = new HashSet<CriterioFilas>();
            this.ValoracionAHPs = new HashSet<ValoracionAHPs>();
        }
    
        public int CriterioMatrizId { get; set; }
        public bool Consistencia { get; set; }
        public Nullable<int> ExpertoEnProyecto_ExpertoEnProyectoId { get; set; }
    
        public virtual ICollection<CriterioFilas> CriterioFilas { get; set; }
        public virtual ExpertosEnProyecto ExpertosEnProyecto { get; set; }
        public virtual ICollection<ValoracionAHPs> ValoracionAHPs { get; set; }
    }
}
