//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OWAOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriterioCeldas
    {
        public int CriterioCeldaId { get; set; }
        public int Fila { get; set; }
        public int Columna { get; set; }
        public double Valor { get; set; }
        public int CriterioId { get; set; }
        public Nullable<int> CriterioFila_CriterioFilaId { get; set; }
    
        public virtual CriterioFilas CriterioFilas { get; set; }
        public virtual Criterios Criterios { get; set; }
    }
}
