//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OWAOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expertos
    {
        public Expertos()
        {
            this.ExpertosEnProyecto = new HashSet<ExpertosEnProyecto>();
            this.Proyectos = new HashSet<Proyectos>();
        }
    
        public int ExpertoId { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        public bool Administrador { get; set; }
    
        public virtual ICollection<ExpertosEnProyecto> ExpertosEnProyecto { get; set; }
        public virtual ICollection<Proyectos> Proyectos { get; set; }
    }
}
