//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OWAOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValoracionAHPs
    {
        public ValoracionAHPs()
        {
            this.AlternativaMatrizs = new HashSet<AlternativaMatrizs>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CriterioMatriz_CriterioMatrizId { get; set; }
    
        public virtual ICollection<AlternativaMatrizs> AlternativaMatrizs { get; set; }
        public virtual CriterioMatrizs CriterioMatrizs { get; set; }
        public virtual ExpertosEnProyecto ExpertosEnProyecto { get; set; }
    }
}
