//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OWAOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValorCriterios
    {
        public int ValorCriterioId { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public double ValorILNumerico { get; set; }
        public string ValorILLinguistico { get; set; }
        public int AlternativaIL_AlternativaILId { get; set; }
    
        public virtual AlternativaILs AlternativaILs { get; set; }
    }
}
