//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace sisexperto
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class gisiabaseEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto gisiabaseEntities usando la cadena de conexión encontrada en la sección 'gisiabaseEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public gisiabaseEntities() : base("name=gisiabaseEntities", "gisiabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto gisiabaseEntities.
        /// </summary>
        public gisiabaseEntities(string connectionString) : base(connectionString, "gisiabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto gisiabaseEntities.
        /// </summary>
        public gisiabaseEntities(EntityConnection connection) : base(connection, "gisiabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<alternativa> alternativa
        {
            get
            {
                if ((_alternativa == null))
                {
                    _alternativa = base.CreateObjectSet<alternativa>("alternativa");
                }
                return _alternativa;
            }
        }
        private ObjectSet<alternativa> _alternativa;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<comparacion_alternativa> comparacion_alternativa
        {
            get
            {
                if ((_comparacion_alternativa == null))
                {
                    _comparacion_alternativa = base.CreateObjectSet<comparacion_alternativa>("comparacion_alternativa");
                }
                return _comparacion_alternativa;
            }
        }
        private ObjectSet<comparacion_alternativa> _comparacion_alternativa;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<comparacion_criterio> comparacion_criterio
        {
            get
            {
                if ((_comparacion_criterio == null))
                {
                    _comparacion_criterio = base.CreateObjectSet<comparacion_criterio>("comparacion_criterio");
                }
                return _comparacion_criterio;
            }
        }
        private ObjectSet<comparacion_criterio> _comparacion_criterio;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<criterio> criterio
        {
            get
            {
                if ((_criterio == null))
                {
                    _criterio = base.CreateObjectSet<criterio>("criterio");
                }
                return _criterio;
            }
        }
        private ObjectSet<criterio> _criterio;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<experto> experto
        {
            get
            {
                if ((_experto == null))
                {
                    _experto = base.CreateObjectSet<experto>("experto");
                }
                return _experto;
            }
        }
        private ObjectSet<experto> _experto;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<experto_proyecto> experto_proyecto
        {
            get
            {
                if ((_experto_proyecto == null))
                {
                    _experto_proyecto = base.CreateObjectSet<experto_proyecto>("experto_proyecto");
                }
                return _experto_proyecto;
            }
        }
        private ObjectSet<experto_proyecto> _experto_proyecto;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<proyecto> proyecto
        {
            get
            {
                if ((_proyecto == null))
                {
                    _proyecto = base.CreateObjectSet<proyecto>("proyecto");
                }
                return _proyecto;
            }
        }
        private ObjectSet<proyecto> _proyecto;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet alternativa. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToalternativa(alternativa alternativa)
        {
            base.AddObject("alternativa", alternativa);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet comparacion_alternativa. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTocomparacion_alternativa(comparacion_alternativa comparacion_alternativa)
        {
            base.AddObject("comparacion_alternativa", comparacion_alternativa);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet comparacion_criterio. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTocomparacion_criterio(comparacion_criterio comparacion_criterio)
        {
            base.AddObject("comparacion_criterio", comparacion_criterio);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet criterio. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTocriterio(criterio criterio)
        {
            base.AddObject("criterio", criterio);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet experto. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToexperto(experto experto)
        {
            base.AddObject("experto", experto);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet experto_proyecto. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToexperto_proyecto(experto_proyecto experto_proyecto)
        {
            base.AddObject("experto_proyecto", experto_proyecto);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet proyecto. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToproyecto(proyecto proyecto)
        {
            base.AddObject("proyecto", proyecto);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gisiabaseModel", Name="alternativa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class alternativa : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto alternativa.
        /// </summary>
        /// <param name="id_alternativa">Valor inicial de la propiedad id_alternativa.</param>
        /// <param name="id_proyecto">Valor inicial de la propiedad id_proyecto.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        public static alternativa Createalternativa(global::System.Int32 id_alternativa, global::System.Int32 id_proyecto, global::System.String nombre)
        {
            alternativa alternativa = new alternativa();
            alternativa.id_alternativa = id_alternativa;
            alternativa.id_proyecto = id_proyecto;
            alternativa.nombre = nombre;
            return alternativa;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_alternativa
        {
            get
            {
                return _id_alternativa;
            }
            set
            {
                if (_id_alternativa != value)
                {
                    Onid_alternativaChanging(value);
                    ReportPropertyChanging("id_alternativa");
                    _id_alternativa = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_alternativa");
                    Onid_alternativaChanged();
                }
            }
        }
        private global::System.Int32 _id_alternativa;
        partial void Onid_alternativaChanging(global::System.Int32 value);
        partial void Onid_alternativaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_proyecto
        {
            get
            {
                return _id_proyecto;
            }
            set
            {
                Onid_proyectoChanging(value);
                ReportPropertyChanging("id_proyecto");
                _id_proyecto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_proyecto");
                Onid_proyectoChanged();
            }
        }
        private global::System.Int32 _id_proyecto;
        partial void Onid_proyectoChanging(global::System.Int32 value);
        partial void Onid_proyectoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gisiabaseModel", Name="comparacion_alternativa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class comparacion_alternativa : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto comparacion_alternativa.
        /// </summary>
        /// <param name="id_proyecto">Valor inicial de la propiedad id_proyecto.</param>
        /// <param name="id_experto">Valor inicial de la propiedad id_experto.</param>
        /// <param name="id_criterio">Valor inicial de la propiedad id_criterio.</param>
        /// <param name="id_alternativa1">Valor inicial de la propiedad id_alternativa1.</param>
        /// <param name="id_alternativa2">Valor inicial de la propiedad id_alternativa2.</param>
        public static comparacion_alternativa Createcomparacion_alternativa(global::System.Int32 id_proyecto, global::System.Int32 id_experto, global::System.Int32 id_criterio, global::System.Int32 id_alternativa1, global::System.Int32 id_alternativa2)
        {
            comparacion_alternativa comparacion_alternativa = new comparacion_alternativa();
            comparacion_alternativa.id_proyecto = id_proyecto;
            comparacion_alternativa.id_experto = id_experto;
            comparacion_alternativa.id_criterio = id_criterio;
            comparacion_alternativa.id_alternativa1 = id_alternativa1;
            comparacion_alternativa.id_alternativa2 = id_alternativa2;
            return comparacion_alternativa;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_proyecto
        {
            get
            {
                return _id_proyecto;
            }
            set
            {
                if (_id_proyecto != value)
                {
                    Onid_proyectoChanging(value);
                    ReportPropertyChanging("id_proyecto");
                    _id_proyecto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_proyecto");
                    Onid_proyectoChanged();
                }
            }
        }
        private global::System.Int32 _id_proyecto;
        partial void Onid_proyectoChanging(global::System.Int32 value);
        partial void Onid_proyectoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_experto
        {
            get
            {
                return _id_experto;
            }
            set
            {
                if (_id_experto != value)
                {
                    Onid_expertoChanging(value);
                    ReportPropertyChanging("id_experto");
                    _id_experto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_experto");
                    Onid_expertoChanged();
                }
            }
        }
        private global::System.Int32 _id_experto;
        partial void Onid_expertoChanging(global::System.Int32 value);
        partial void Onid_expertoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_criterio
        {
            get
            {
                return _id_criterio;
            }
            set
            {
                if (_id_criterio != value)
                {
                    Onid_criterioChanging(value);
                    ReportPropertyChanging("id_criterio");
                    _id_criterio = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_criterio");
                    Onid_criterioChanged();
                }
            }
        }
        private global::System.Int32 _id_criterio;
        partial void Onid_criterioChanging(global::System.Int32 value);
        partial void Onid_criterioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_alternativa1
        {
            get
            {
                return _id_alternativa1;
            }
            set
            {
                if (_id_alternativa1 != value)
                {
                    Onid_alternativa1Changing(value);
                    ReportPropertyChanging("id_alternativa1");
                    _id_alternativa1 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_alternativa1");
                    Onid_alternativa1Changed();
                }
            }
        }
        private global::System.Int32 _id_alternativa1;
        partial void Onid_alternativa1Changing(global::System.Int32 value);
        partial void Onid_alternativa1Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_alternativa2
        {
            get
            {
                return _id_alternativa2;
            }
            set
            {
                if (_id_alternativa2 != value)
                {
                    Onid_alternativa2Changing(value);
                    ReportPropertyChanging("id_alternativa2");
                    _id_alternativa2 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_alternativa2");
                    Onid_alternativa2Changed();
                }
            }
        }
        private global::System.Int32 _id_alternativa2;
        partial void Onid_alternativa2Changing(global::System.Int32 value);
        partial void Onid_alternativa2Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> valor
        {
            get
            {
                return _valor;
            }
            set
            {
                OnvalorChanging(value);
                ReportPropertyChanging("valor");
                _valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("valor");
                OnvalorChanged();
            }
        }
        private Nullable<global::System.Double> _valor;
        partial void OnvalorChanging(Nullable<global::System.Double> value);
        partial void OnvalorChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gisiabaseModel", Name="comparacion_criterio")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class comparacion_criterio : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto comparacion_criterio.
        /// </summary>
        /// <param name="id_proyecto">Valor inicial de la propiedad id_proyecto.</param>
        /// <param name="id_experto">Valor inicial de la propiedad id_experto.</param>
        /// <param name="id_criterio1">Valor inicial de la propiedad id_criterio1.</param>
        /// <param name="id_criterio2">Valor inicial de la propiedad id_criterio2.</param>
        public static comparacion_criterio Createcomparacion_criterio(global::System.Int32 id_proyecto, global::System.Int32 id_experto, global::System.Int32 id_criterio1, global::System.Int32 id_criterio2)
        {
            comparacion_criterio comparacion_criterio = new comparacion_criterio();
            comparacion_criterio.id_proyecto = id_proyecto;
            comparacion_criterio.id_experto = id_experto;
            comparacion_criterio.id_criterio1 = id_criterio1;
            comparacion_criterio.id_criterio2 = id_criterio2;
            return comparacion_criterio;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_proyecto
        {
            get
            {
                return _id_proyecto;
            }
            set
            {
                if (_id_proyecto != value)
                {
                    Onid_proyectoChanging(value);
                    ReportPropertyChanging("id_proyecto");
                    _id_proyecto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_proyecto");
                    Onid_proyectoChanged();
                }
            }
        }
        private global::System.Int32 _id_proyecto;
        partial void Onid_proyectoChanging(global::System.Int32 value);
        partial void Onid_proyectoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_experto
        {
            get
            {
                return _id_experto;
            }
            set
            {
                if (_id_experto != value)
                {
                    Onid_expertoChanging(value);
                    ReportPropertyChanging("id_experto");
                    _id_experto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_experto");
                    Onid_expertoChanged();
                }
            }
        }
        private global::System.Int32 _id_experto;
        partial void Onid_expertoChanging(global::System.Int32 value);
        partial void Onid_expertoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_criterio1
        {
            get
            {
                return _id_criterio1;
            }
            set
            {
                if (_id_criterio1 != value)
                {
                    Onid_criterio1Changing(value);
                    ReportPropertyChanging("id_criterio1");
                    _id_criterio1 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_criterio1");
                    Onid_criterio1Changed();
                }
            }
        }
        private global::System.Int32 _id_criterio1;
        partial void Onid_criterio1Changing(global::System.Int32 value);
        partial void Onid_criterio1Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_criterio2
        {
            get
            {
                return _id_criterio2;
            }
            set
            {
                if (_id_criterio2 != value)
                {
                    Onid_criterio2Changing(value);
                    ReportPropertyChanging("id_criterio2");
                    _id_criterio2 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_criterio2");
                    Onid_criterio2Changed();
                }
            }
        }
        private global::System.Int32 _id_criterio2;
        partial void Onid_criterio2Changing(global::System.Int32 value);
        partial void Onid_criterio2Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> valor
        {
            get
            {
                return _valor;
            }
            set
            {
                OnvalorChanging(value);
                ReportPropertyChanging("valor");
                _valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("valor");
                OnvalorChanged();
            }
        }
        private Nullable<global::System.Double> _valor;
        partial void OnvalorChanging(Nullable<global::System.Double> value);
        partial void OnvalorChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gisiabaseModel", Name="criterio")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class criterio : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto criterio.
        /// </summary>
        /// <param name="id_criterio">Valor inicial de la propiedad id_criterio.</param>
        /// <param name="id_proyecto">Valor inicial de la propiedad id_proyecto.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        public static criterio Createcriterio(global::System.Int32 id_criterio, global::System.Int32 id_proyecto, global::System.String nombre)
        {
            criterio criterio = new criterio();
            criterio.id_criterio = id_criterio;
            criterio.id_proyecto = id_proyecto;
            criterio.nombre = nombre;
            return criterio;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_criterio
        {
            get
            {
                return _id_criterio;
            }
            set
            {
                if (_id_criterio != value)
                {
                    Onid_criterioChanging(value);
                    ReportPropertyChanging("id_criterio");
                    _id_criterio = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_criterio");
                    Onid_criterioChanged();
                }
            }
        }
        private global::System.Int32 _id_criterio;
        partial void Onid_criterioChanging(global::System.Int32 value);
        partial void Onid_criterioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_proyecto
        {
            get
            {
                return _id_proyecto;
            }
            set
            {
                Onid_proyectoChanging(value);
                ReportPropertyChanging("id_proyecto");
                _id_proyecto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_proyecto");
                Onid_proyectoChanged();
            }
        }
        private global::System.Int32 _id_proyecto;
        partial void Onid_proyectoChanging(global::System.Int32 value);
        partial void Onid_proyectoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gisiabaseModel", Name="experto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class experto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto experto.
        /// </summary>
        /// <param name="id_experto">Valor inicial de la propiedad id_experto.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="apellido">Valor inicial de la propiedad apellido.</param>
        /// <param name="nom_usuario">Valor inicial de la propiedad nom_usuario.</param>
        /// <param name="clave">Valor inicial de la propiedad clave.</param>
        public static experto Createexperto(global::System.Int32 id_experto, global::System.String nombre, global::System.String apellido, global::System.String nom_usuario, global::System.String clave)
        {
            experto experto = new experto();
            experto.id_experto = id_experto;
            experto.nombre = nombre;
            experto.apellido = apellido;
            experto.nom_usuario = nom_usuario;
            experto.clave = clave;
            return experto;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_experto
        {
            get
            {
                return _id_experto;
            }
            set
            {
                if (_id_experto != value)
                {
                    Onid_expertoChanging(value);
                    ReportPropertyChanging("id_experto");
                    _id_experto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_experto");
                    Onid_expertoChanged();
                }
            }
        }
        private global::System.Int32 _id_experto;
        partial void Onid_expertoChanging(global::System.Int32 value);
        partial void Onid_expertoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String apellido
        {
            get
            {
                return _apellido;
            }
            set
            {
                OnapellidoChanging(value);
                ReportPropertyChanging("apellido");
                _apellido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("apellido");
                OnapellidoChanged();
            }
        }
        private global::System.String _apellido;
        partial void OnapellidoChanging(global::System.String value);
        partial void OnapellidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nom_usuario
        {
            get
            {
                return _nom_usuario;
            }
            set
            {
                Onnom_usuarioChanging(value);
                ReportPropertyChanging("nom_usuario");
                _nom_usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nom_usuario");
                Onnom_usuarioChanged();
            }
        }
        private global::System.String _nom_usuario;
        partial void Onnom_usuarioChanging(global::System.String value);
        partial void Onnom_usuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String clave
        {
            get
            {
                return _clave;
            }
            set
            {
                OnclaveChanging(value);
                ReportPropertyChanging("clave");
                _clave = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("clave");
                OnclaveChanged();
            }
        }
        private global::System.String _clave;
        partial void OnclaveChanging(global::System.String value);
        partial void OnclaveChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gisiabaseModel", Name="experto_proyecto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class experto_proyecto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto experto_proyecto.
        /// </summary>
        /// <param name="id_proyecto">Valor inicial de la propiedad id_proyecto.</param>
        /// <param name="id_experto">Valor inicial de la propiedad id_experto.</param>
        public static experto_proyecto Createexperto_proyecto(global::System.Int32 id_proyecto, global::System.Int32 id_experto)
        {
            experto_proyecto experto_proyecto = new experto_proyecto();
            experto_proyecto.id_proyecto = id_proyecto;
            experto_proyecto.id_experto = id_experto;
            return experto_proyecto;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_proyecto
        {
            get
            {
                return _id_proyecto;
            }
            set
            {
                if (_id_proyecto != value)
                {
                    Onid_proyectoChanging(value);
                    ReportPropertyChanging("id_proyecto");
                    _id_proyecto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_proyecto");
                    Onid_proyectoChanged();
                }
            }
        }
        private global::System.Int32 _id_proyecto;
        partial void Onid_proyectoChanging(global::System.Int32 value);
        partial void Onid_proyectoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_experto
        {
            get
            {
                return _id_experto;
            }
            set
            {
                if (_id_experto != value)
                {
                    Onid_expertoChanging(value);
                    ReportPropertyChanging("id_experto");
                    _id_experto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_experto");
                    Onid_expertoChanged();
                }
            }
        }
        private global::System.Int32 _id_experto;
        partial void Onid_expertoChanging(global::System.Int32 value);
        partial void Onid_expertoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> ponderacion
        {
            get
            {
                return _ponderacion;
            }
            set
            {
                OnponderacionChanging(value);
                ReportPropertyChanging("ponderacion");
                _ponderacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ponderacion");
                OnponderacionChanged();
            }
        }
        private Nullable<global::System.Double> _ponderacion;
        partial void OnponderacionChanging(Nullable<global::System.Double> value);
        partial void OnponderacionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gisiabaseModel", Name="proyecto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class proyecto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto proyecto.
        /// </summary>
        /// <param name="id_proyecto">Valor inicial de la propiedad id_proyecto.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        public static proyecto Createproyecto(global::System.Int32 id_proyecto, global::System.String nombre)
        {
            proyecto proyecto = new proyecto();
            proyecto.id_proyecto = id_proyecto;
            proyecto.nombre = nombre;
            return proyecto;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_proyecto
        {
            get
            {
                return _id_proyecto;
            }
            set
            {
                if (_id_proyecto != value)
                {
                    Onid_proyectoChanging(value);
                    ReportPropertyChanging("id_proyecto");
                    _id_proyecto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_proyecto");
                    Onid_proyectoChanged();
                }
            }
        }
        private global::System.Int32 _id_proyecto;
        partial void Onid_proyectoChanging(global::System.Int32 value);
        partial void Onid_proyectoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String objetivo
        {
            get
            {
                return _objetivo;
            }
            set
            {
                OnobjetivoChanging(value);
                ReportPropertyChanging("objetivo");
                _objetivo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("objetivo");
                OnobjetivoChanged();
            }
        }
        private global::System.String _objetivo;
        partial void OnobjetivoChanging(global::System.String value);
        partial void OnobjetivoChanged();

        #endregion
    
    }

    #endregion
    
}
