//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace sisexperto
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class gisiabaseEntities2 : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto gisiabaseEntities2 usando la cadena de conexión encontrada en la sección 'gisiabaseEntities2' del archivo de configuración de la aplicación.
        /// </summary>
        public gisiabaseEntities2() : base("name=gisiabaseEntities2", "gisiabaseEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto gisiabaseEntities2.
        /// </summary>
        public gisiabaseEntities2(string connectionString) : base(connectionString, "gisiabaseEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto gisiabaseEntities2.
        /// </summary>
        public gisiabaseEntities2(EntityConnection connection) : base(connection, "gisiabaseEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<alternativa> alternativa
        {
            get
            {
                if ((_alternativa == null))
                {
                    _alternativa = base.CreateObjectSet<alternativa>("alternativa");
                }
                return _alternativa;
            }
        }
        private ObjectSet<alternativa> _alternativa;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<comparacion_alternativa> comparacion_alternativa
        {
            get
            {
                if ((_comparacion_alternativa == null))
                {
                    _comparacion_alternativa = base.CreateObjectSet<comparacion_alternativa>("comparacion_alternativa");
                }
                return _comparacion_alternativa;
            }
        }
        private ObjectSet<comparacion_alternativa> _comparacion_alternativa;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<comparacion_criterio> comparacion_criterio
        {
            get
            {
                if ((_comparacion_criterio == null))
                {
                    _comparacion_criterio = base.CreateObjectSet<comparacion_criterio>("comparacion_criterio");
                }
                return _comparacion_criterio;
            }
        }
        private ObjectSet<comparacion_criterio> _comparacion_criterio;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<criterio> criterio
        {
            get
            {
                if ((_criterio == null))
                {
                    _criterio = base.CreateObjectSet<criterio>("criterio");
                }
                return _criterio;
            }
        }
        private ObjectSet<criterio> _criterio;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<experto> experto
        {
            get
            {
                if ((_experto == null))
                {
                    _experto = base.CreateObjectSet<experto>("experto");
                }
                return _experto;
            }
        }
        private ObjectSet<experto> _experto;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<experto_proyecto> experto_proyecto
        {
            get
            {
                if ((_experto_proyecto == null))
                {
                    _experto_proyecto = base.CreateObjectSet<experto_proyecto>("experto_proyecto");
                }
                return _experto_proyecto;
            }
        }
        private ObjectSet<experto_proyecto> _experto_proyecto;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<proyecto> proyecto
        {
            get
            {
                if ((_proyecto == null))
                {
                    _proyecto = base.CreateObjectSet<proyecto>("proyecto");
                }
                return _proyecto;
            }
        }
        private ObjectSet<proyecto> _proyecto;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<ILSet> ILSetSet
        {
            get
            {
                if ((_ILSetSet == null))
                {
                    _ILSetSet = base.CreateObjectSet<ILSet>("ILSetSet");
                }
                return _ILSetSet;
            }
        }
        private ObjectSet<ILSet> _ILSetSet;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<matriz_alternativa> matriz_alternativa
        {
            get
            {
                if ((_matriz_alternativa == null))
                {
                    _matriz_alternativa = base.CreateObjectSet<matriz_alternativa>("matriz_alternativa");
                }
                return _matriz_alternativa;
            }
        }
        private ObjectSet<matriz_alternativa> _matriz_alternativa;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<matriz_criterio> matriz_criterio
        {
            get
            {
                if ((_matriz_criterio == null))
                {
                    _matriz_criterio = base.CreateObjectSet<matriz_criterio>("matriz_criterio");
                }
                return _matriz_criterio;
            }
        }
        private ObjectSet<matriz_criterio> _matriz_criterio;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet alternativa. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToalternativa(alternativa alternativa)
        {
            base.AddObject("alternativa", alternativa);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet comparacion_alternativa. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTocomparacion_alternativa(comparacion_alternativa comparacion_alternativa)
        {
            base.AddObject("comparacion_alternativa", comparacion_alternativa);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet comparacion_criterio. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTocomparacion_criterio(comparacion_criterio comparacion_criterio)
        {
            base.AddObject("comparacion_criterio", comparacion_criterio);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet criterio. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTocriterio(criterio criterio)
        {
            base.AddObject("criterio", criterio);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet experto. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToexperto(experto experto)
        {
            base.AddObject("experto", experto);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet experto_proyecto. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToexperto_proyecto(experto_proyecto experto_proyecto)
        {
            base.AddObject("experto_proyecto", experto_proyecto);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet proyecto. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToproyecto(proyecto proyecto)
        {
            base.AddObject("proyecto", proyecto);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ILSetSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToILSetSet(ILSet iLSet)
        {
            base.AddObject("ILSetSet", iLSet);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet matriz_alternativa. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTomatriz_alternativa(matriz_alternativa matriz_alternativa)
        {
            base.AddObject("matriz_alternativa", matriz_alternativa);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet matriz_criterio. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTomatriz_criterio(matriz_criterio matriz_criterio)
        {
            base.AddObject("matriz_criterio", matriz_criterio);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gisiabaseModel1", Name="alternativa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class alternativa : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto alternativa.
        /// </summary>
        /// <param name="id_alternativa">Valor inicial de la propiedad id_alternativa.</param>
        /// <param name="id_proyecto">Valor inicial de la propiedad id_proyecto.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        public static alternativa Createalternativa(global::System.Int32 id_alternativa, global::System.Int32 id_proyecto, global::System.String nombre)
        {
            alternativa alternativa = new alternativa();
            alternativa.id_alternativa = id_alternativa;
            alternativa.id_proyecto = id_proyecto;
            alternativa.nombre = nombre;
            return alternativa;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_alternativa
        {
            get
            {
                return _id_alternativa;
            }
            set
            {
                if (_id_alternativa != value)
                {
                    Onid_alternativaChanging(value);
                    ReportPropertyChanging("id_alternativa");
                    _id_alternativa = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_alternativa");
                    Onid_alternativaChanged();
                }
            }
        }
        private global::System.Int32 _id_alternativa;
        partial void Onid_alternativaChanging(global::System.Int32 value);
        partial void Onid_alternativaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_proyecto
        {
            get
            {
                return _id_proyecto;
            }
            set
            {
                Onid_proyectoChanging(value);
                ReportPropertyChanging("id_proyecto");
                _id_proyecto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_proyecto");
                Onid_proyectoChanged();
            }
        }
        private global::System.Int32 _id_proyecto;
        partial void Onid_proyectoChanging(global::System.Int32 value);
        partial void Onid_proyectoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gisiabaseModel1", Name="comparacion_alternativa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class comparacion_alternativa : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto comparacion_alternativa.
        /// </summary>
        /// <param name="id_comparacion">Valor inicial de la propiedad id_comparacion.</param>
        /// <param name="id_proyecto">Valor inicial de la propiedad id_proyecto.</param>
        /// <param name="id_experto">Valor inicial de la propiedad id_experto.</param>
        /// <param name="id_criterio">Valor inicial de la propiedad id_criterio.</param>
        /// <param name="id_alternativa1">Valor inicial de la propiedad id_alternativa1.</param>
        /// <param name="id_alternativa2">Valor inicial de la propiedad id_alternativa2.</param>
        /// <param name="pos_fila">Valor inicial de la propiedad pos_fila.</param>
        /// <param name="pos_columna">Valor inicial de la propiedad pos_columna.</param>
        public static comparacion_alternativa Createcomparacion_alternativa(global::System.Int32 id_comparacion, global::System.Int32 id_proyecto, global::System.Int32 id_experto, global::System.Int32 id_criterio, global::System.Int32 id_alternativa1, global::System.Int32 id_alternativa2, global::System.Int32 pos_fila, global::System.Int32 pos_columna)
        {
            comparacion_alternativa comparacion_alternativa = new comparacion_alternativa();
            comparacion_alternativa.id_comparacion = id_comparacion;
            comparacion_alternativa.id_proyecto = id_proyecto;
            comparacion_alternativa.id_experto = id_experto;
            comparacion_alternativa.id_criterio = id_criterio;
            comparacion_alternativa.id_alternativa1 = id_alternativa1;
            comparacion_alternativa.id_alternativa2 = id_alternativa2;
            comparacion_alternativa.pos_fila = pos_fila;
            comparacion_alternativa.pos_columna = pos_columna;
            return comparacion_alternativa;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_comparacion
        {
            get
            {
                return _id_comparacion;
            }
            set
            {
                if (_id_comparacion != value)
                {
                    Onid_comparacionChanging(value);
                    ReportPropertyChanging("id_comparacion");
                    _id_comparacion = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_comparacion");
                    Onid_comparacionChanged();
                }
            }
        }
        private global::System.Int32 _id_comparacion;
        partial void Onid_comparacionChanging(global::System.Int32 value);
        partial void Onid_comparacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_proyecto
        {
            get
            {
                return _id_proyecto;
            }
            set
            {
                Onid_proyectoChanging(value);
                ReportPropertyChanging("id_proyecto");
                _id_proyecto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_proyecto");
                Onid_proyectoChanged();
            }
        }
        private global::System.Int32 _id_proyecto;
        partial void Onid_proyectoChanging(global::System.Int32 value);
        partial void Onid_proyectoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_experto
        {
            get
            {
                return _id_experto;
            }
            set
            {
                Onid_expertoChanging(value);
                ReportPropertyChanging("id_experto");
                _id_experto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_experto");
                Onid_expertoChanged();
            }
        }
        private global::System.Int32 _id_experto;
        partial void Onid_expertoChanging(global::System.Int32 value);
        partial void Onid_expertoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_criterio
        {
            get
            {
                return _id_criterio;
            }
            set
            {
                Onid_criterioChanging(value);
                ReportPropertyChanging("id_criterio");
                _id_criterio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_criterio");
                Onid_criterioChanged();
            }
        }
        private global::System.Int32 _id_criterio;
        partial void Onid_criterioChanging(global::System.Int32 value);
        partial void Onid_criterioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_alternativa1
        {
            get
            {
                return _id_alternativa1;
            }
            set
            {
                Onid_alternativa1Changing(value);
                ReportPropertyChanging("id_alternativa1");
                _id_alternativa1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_alternativa1");
                Onid_alternativa1Changed();
            }
        }
        private global::System.Int32 _id_alternativa1;
        partial void Onid_alternativa1Changing(global::System.Int32 value);
        partial void Onid_alternativa1Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_alternativa2
        {
            get
            {
                return _id_alternativa2;
            }
            set
            {
                Onid_alternativa2Changing(value);
                ReportPropertyChanging("id_alternativa2");
                _id_alternativa2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_alternativa2");
                Onid_alternativa2Changed();
            }
        }
        private global::System.Int32 _id_alternativa2;
        partial void Onid_alternativa2Changing(global::System.Int32 value);
        partial void Onid_alternativa2Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pos_fila
        {
            get
            {
                return _pos_fila;
            }
            set
            {
                Onpos_filaChanging(value);
                ReportPropertyChanging("pos_fila");
                _pos_fila = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pos_fila");
                Onpos_filaChanged();
            }
        }
        private global::System.Int32 _pos_fila;
        partial void Onpos_filaChanging(global::System.Int32 value);
        partial void Onpos_filaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pos_columna
        {
            get
            {
                return _pos_columna;
            }
            set
            {
                Onpos_columnaChanging(value);
                ReportPropertyChanging("pos_columna");
                _pos_columna = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pos_columna");
                Onpos_columnaChanged();
            }
        }
        private global::System.Int32 _pos_columna;
        partial void Onpos_columnaChanging(global::System.Int32 value);
        partial void Onpos_columnaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> valor
        {
            get
            {
                return _valor;
            }
            set
            {
                OnvalorChanging(value);
                ReportPropertyChanging("valor");
                _valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("valor");
                OnvalorChanged();
            }
        }
        private Nullable<global::System.Double> _valor;
        partial void OnvalorChanging(Nullable<global::System.Double> value);
        partial void OnvalorChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gisiabaseModel1", Name="comparacion_criterio")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class comparacion_criterio : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto comparacion_criterio.
        /// </summary>
        /// <param name="id_comparacion">Valor inicial de la propiedad id_comparacion.</param>
        /// <param name="id_proyecto">Valor inicial de la propiedad id_proyecto.</param>
        /// <param name="id_experto">Valor inicial de la propiedad id_experto.</param>
        /// <param name="id_criterio1">Valor inicial de la propiedad id_criterio1.</param>
        /// <param name="id_criterio2">Valor inicial de la propiedad id_criterio2.</param>
        /// <param name="pos_fila">Valor inicial de la propiedad pos_fila.</param>
        /// <param name="pos_columna">Valor inicial de la propiedad pos_columna.</param>
        public static comparacion_criterio Createcomparacion_criterio(global::System.Int32 id_comparacion, global::System.Int32 id_proyecto, global::System.Int32 id_experto, global::System.Int32 id_criterio1, global::System.Int32 id_criterio2, global::System.Int32 pos_fila, global::System.Int32 pos_columna)
        {
            comparacion_criterio comparacion_criterio = new comparacion_criterio();
            comparacion_criterio.id_comparacion = id_comparacion;
            comparacion_criterio.id_proyecto = id_proyecto;
            comparacion_criterio.id_experto = id_experto;
            comparacion_criterio.id_criterio1 = id_criterio1;
            comparacion_criterio.id_criterio2 = id_criterio2;
            comparacion_criterio.pos_fila = pos_fila;
            comparacion_criterio.pos_columna = pos_columna;
            return comparacion_criterio;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_comparacion
        {
            get
            {
                return _id_comparacion;
            }
            set
            {
                if (_id_comparacion != value)
                {
                    Onid_comparacionChanging(value);
                    ReportPropertyChanging("id_comparacion");
                    _id_comparacion = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_comparacion");
                    Onid_comparacionChanged();
                }
            }
        }
        private global::System.Int32 _id_comparacion;
        partial void Onid_comparacionChanging(global::System.Int32 value);
        partial void Onid_comparacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_proyecto
        {
            get
            {
                return _id_proyecto;
            }
            set
            {
                Onid_proyectoChanging(value);
                ReportPropertyChanging("id_proyecto");
                _id_proyecto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_proyecto");
                Onid_proyectoChanged();
            }
        }
        private global::System.Int32 _id_proyecto;
        partial void Onid_proyectoChanging(global::System.Int32 value);
        partial void Onid_proyectoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_experto
        {
            get
            {
                return _id_experto;
            }
            set
            {
                Onid_expertoChanging(value);
                ReportPropertyChanging("id_experto");
                _id_experto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_experto");
                Onid_expertoChanged();
            }
        }
        private global::System.Int32 _id_experto;
        partial void Onid_expertoChanging(global::System.Int32 value);
        partial void Onid_expertoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_criterio1
        {
            get
            {
                return _id_criterio1;
            }
            set
            {
                Onid_criterio1Changing(value);
                ReportPropertyChanging("id_criterio1");
                _id_criterio1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_criterio1");
                Onid_criterio1Changed();
            }
        }
        private global::System.Int32 _id_criterio1;
        partial void Onid_criterio1Changing(global::System.Int32 value);
        partial void Onid_criterio1Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_criterio2
        {
            get
            {
                return _id_criterio2;
            }
            set
            {
                Onid_criterio2Changing(value);
                ReportPropertyChanging("id_criterio2");
                _id_criterio2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_criterio2");
                Onid_criterio2Changed();
            }
        }
        private global::System.Int32 _id_criterio2;
        partial void Onid_criterio2Changing(global::System.Int32 value);
        partial void Onid_criterio2Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pos_fila
        {
            get
            {
                return _pos_fila;
            }
            set
            {
                Onpos_filaChanging(value);
                ReportPropertyChanging("pos_fila");
                _pos_fila = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pos_fila");
                Onpos_filaChanged();
            }
        }
        private global::System.Int32 _pos_fila;
        partial void Onpos_filaChanging(global::System.Int32 value);
        partial void Onpos_filaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pos_columna
        {
            get
            {
                return _pos_columna;
            }
            set
            {
                Onpos_columnaChanging(value);
                ReportPropertyChanging("pos_columna");
                _pos_columna = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pos_columna");
                Onpos_columnaChanged();
            }
        }
        private global::System.Int32 _pos_columna;
        partial void Onpos_columnaChanging(global::System.Int32 value);
        partial void Onpos_columnaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> valor
        {
            get
            {
                return _valor;
            }
            set
            {
                OnvalorChanging(value);
                ReportPropertyChanging("valor");
                _valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("valor");
                OnvalorChanged();
            }
        }
        private Nullable<global::System.Double> _valor;
        partial void OnvalorChanging(Nullable<global::System.Double> value);
        partial void OnvalorChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gisiabaseModel1", Name="criterio")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class criterio : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto criterio.
        /// </summary>
        /// <param name="id_criterio">Valor inicial de la propiedad id_criterio.</param>
        /// <param name="id_proyecto">Valor inicial de la propiedad id_proyecto.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="iLPonderacion">Valor inicial de la propiedad ILPonderacion.</param>
        public static criterio Createcriterio(global::System.Int32 id_criterio, global::System.Int32 id_proyecto, global::System.String nombre, global::System.Double iLPonderacion)
        {
            criterio criterio = new criterio();
            criterio.id_criterio = id_criterio;
            criterio.id_proyecto = id_proyecto;
            criterio.nombre = nombre;
            criterio.ILPonderacion = iLPonderacion;
            return criterio;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_criterio
        {
            get
            {
                return _id_criterio;
            }
            set
            {
                if (_id_criterio != value)
                {
                    Onid_criterioChanging(value);
                    ReportPropertyChanging("id_criterio");
                    _id_criterio = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_criterio");
                    Onid_criterioChanged();
                }
            }
        }
        private global::System.Int32 _id_criterio;
        partial void Onid_criterioChanging(global::System.Int32 value);
        partial void Onid_criterioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_proyecto
        {
            get
            {
                return _id_proyecto;
            }
            set
            {
                Onid_proyectoChanging(value);
                ReportPropertyChanging("id_proyecto");
                _id_proyecto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_proyecto");
                Onid_proyectoChanged();
            }
        }
        private global::System.Int32 _id_proyecto;
        partial void Onid_proyectoChanging(global::System.Int32 value);
        partial void Onid_proyectoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double ILPonderacion
        {
            get
            {
                return _ILPonderacion;
            }
            set
            {
                OnILPonderacionChanging(value);
                ReportPropertyChanging("ILPonderacion");
                _ILPonderacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ILPonderacion");
                OnILPonderacionChanged();
            }
        }
        private global::System.Double _ILPonderacion;
        partial void OnILPonderacionChanging(global::System.Double value);
        partial void OnILPonderacionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gisiabaseModel1", Name="experto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class experto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto experto.
        /// </summary>
        /// <param name="id_experto">Valor inicial de la propiedad id_experto.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="apellido">Valor inicial de la propiedad apellido.</param>
        /// <param name="nom_usuario">Valor inicial de la propiedad nom_usuario.</param>
        /// <param name="clave">Valor inicial de la propiedad clave.</param>
        public static experto Createexperto(global::System.Int32 id_experto, global::System.String nombre, global::System.String apellido, global::System.String nom_usuario, global::System.String clave)
        {
            experto experto = new experto();
            experto.id_experto = id_experto;
            experto.nombre = nombre;
            experto.apellido = apellido;
            experto.nom_usuario = nom_usuario;
            experto.clave = clave;
            return experto;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_experto
        {
            get
            {
                return _id_experto;
            }
            set
            {
                if (_id_experto != value)
                {
                    Onid_expertoChanging(value);
                    ReportPropertyChanging("id_experto");
                    _id_experto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_experto");
                    Onid_expertoChanged();
                }
            }
        }
        private global::System.Int32 _id_experto;
        partial void Onid_expertoChanging(global::System.Int32 value);
        partial void Onid_expertoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String apellido
        {
            get
            {
                return _apellido;
            }
            set
            {
                OnapellidoChanging(value);
                ReportPropertyChanging("apellido");
                _apellido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("apellido");
                OnapellidoChanged();
            }
        }
        private global::System.String _apellido;
        partial void OnapellidoChanging(global::System.String value);
        partial void OnapellidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nom_usuario
        {
            get
            {
                return _nom_usuario;
            }
            set
            {
                Onnom_usuarioChanging(value);
                ReportPropertyChanging("nom_usuario");
                _nom_usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nom_usuario");
                Onnom_usuarioChanged();
            }
        }
        private global::System.String _nom_usuario;
        partial void Onnom_usuarioChanging(global::System.String value);
        partial void Onnom_usuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String clave
        {
            get
            {
                return _clave;
            }
            set
            {
                OnclaveChanging(value);
                ReportPropertyChanging("clave");
                _clave = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("clave");
                OnclaveChanged();
            }
        }
        private global::System.String _clave;
        partial void OnclaveChanging(global::System.String value);
        partial void OnclaveChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gisiabaseModel1", Name="experto_proyecto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class experto_proyecto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto experto_proyecto.
        /// </summary>
        /// <param name="id_asignacion">Valor inicial de la propiedad id_asignacion.</param>
        /// <param name="id_proyecto">Valor inicial de la propiedad id_proyecto.</param>
        /// <param name="id_experto">Valor inicial de la propiedad id_experto.</param>
        /// <param name="ponderacion">Valor inicial de la propiedad ponderacion.</param>
        /// <param name="iLPonderacion">Valor inicial de la propiedad ILPonderacion.</param>
        /// <param name="valoracion_consistente">Valor inicial de la propiedad valoracion_consistente.</param>
        public static experto_proyecto Createexperto_proyecto(global::System.Int32 id_asignacion, global::System.Int32 id_proyecto, global::System.Int32 id_experto, global::System.Double ponderacion, global::System.Double iLPonderacion, global::System.Boolean valoracion_consistente)
        {
            experto_proyecto experto_proyecto = new experto_proyecto();
            experto_proyecto.id_asignacion = id_asignacion;
            experto_proyecto.id_proyecto = id_proyecto;
            experto_proyecto.id_experto = id_experto;
            experto_proyecto.ponderacion = ponderacion;
            experto_proyecto.ILPonderacion = iLPonderacion;
            experto_proyecto.valoracion_consistente = valoracion_consistente;
            return experto_proyecto;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_asignacion
        {
            get
            {
                return _id_asignacion;
            }
            set
            {
                if (_id_asignacion != value)
                {
                    Onid_asignacionChanging(value);
                    ReportPropertyChanging("id_asignacion");
                    _id_asignacion = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_asignacion");
                    Onid_asignacionChanged();
                }
            }
        }
        private global::System.Int32 _id_asignacion;
        partial void Onid_asignacionChanging(global::System.Int32 value);
        partial void Onid_asignacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_proyecto
        {
            get
            {
                return _id_proyecto;
            }
            set
            {
                Onid_proyectoChanging(value);
                ReportPropertyChanging("id_proyecto");
                _id_proyecto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_proyecto");
                Onid_proyectoChanged();
            }
        }
        private global::System.Int32 _id_proyecto;
        partial void Onid_proyectoChanging(global::System.Int32 value);
        partial void Onid_proyectoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_experto
        {
            get
            {
                return _id_experto;
            }
            set
            {
                Onid_expertoChanging(value);
                ReportPropertyChanging("id_experto");
                _id_experto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_experto");
                Onid_expertoChanged();
            }
        }
        private global::System.Int32 _id_experto;
        partial void Onid_expertoChanging(global::System.Int32 value);
        partial void Onid_expertoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double ponderacion
        {
            get
            {
                return _ponderacion;
            }
            set
            {
                OnponderacionChanging(value);
                ReportPropertyChanging("ponderacion");
                _ponderacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ponderacion");
                OnponderacionChanged();
            }
        }
        private global::System.Double _ponderacion;
        partial void OnponderacionChanging(global::System.Double value);
        partial void OnponderacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double ILPonderacion
        {
            get
            {
                return _ILPonderacion;
            }
            set
            {
                OnILPonderacionChanging(value);
                ReportPropertyChanging("ILPonderacion");
                _ILPonderacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ILPonderacion");
                OnILPonderacionChanged();
            }
        }
        private global::System.Double _ILPonderacion;
        partial void OnILPonderacionChanging(global::System.Double value);
        partial void OnILPonderacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean valoracion_consistente
        {
            get
            {
                return _valoracion_consistente;
            }
            set
            {
                Onvaloracion_consistenteChanging(value);
                ReportPropertyChanging("valoracion_consistente");
                _valoracion_consistente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("valoracion_consistente");
                Onvaloracion_consistenteChanged();
            }
        }
        private global::System.Boolean _valoracion_consistente;
        partial void Onvaloracion_consistenteChanging(global::System.Boolean value);
        partial void Onvaloracion_consistenteChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gisiabaseModel1", Name="ILSet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ILSet : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto ILSet.
        /// </summary>
        /// <param name="id_Model">Valor inicial de la propiedad id_Model.</param>
        /// <param name="id_Label">Valor inicial de la propiedad id_Label.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="a">Valor inicial de la propiedad a.</param>
        /// <param name="b">Valor inicial de la propiedad b.</param>
        /// <param name="c">Valor inicial de la propiedad c.</param>
        /// <param name="id_proyecto">Valor inicial de la propiedad id_proyecto.</param>
        /// <param name="id_asignacion">Valor inicial de la propiedad id_asignacion.</param>
        /// <param name="valor">Valor inicial de la propiedad valor.</param>
        public static ILSet CreateILSet(global::System.Int32 id_Model, global::System.String id_Label, global::System.String nombre, global::System.String a, global::System.String b, global::System.String c, global::System.String id_proyecto, global::System.String id_asignacion, global::System.String valor)
        {
            ILSet iLSet = new ILSet();
            iLSet.id_Model = id_Model;
            iLSet.id_Label = id_Label;
            iLSet.nombre = nombre;
            iLSet.a = a;
            iLSet.b = b;
            iLSet.c = c;
            iLSet.id_proyecto = id_proyecto;
            iLSet.id_asignacion = id_asignacion;
            iLSet.valor = valor;
            return iLSet;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Model
        {
            get
            {
                return _id_Model;
            }
            set
            {
                if (_id_Model != value)
                {
                    Onid_ModelChanging(value);
                    ReportPropertyChanging("id_Model");
                    _id_Model = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_Model");
                    Onid_ModelChanged();
                }
            }
        }
        private global::System.Int32 _id_Model;
        partial void Onid_ModelChanging(global::System.Int32 value);
        partial void Onid_ModelChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id_Label
        {
            get
            {
                return _id_Label;
            }
            set
            {
                Onid_LabelChanging(value);
                ReportPropertyChanging("id_Label");
                _id_Label = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("id_Label");
                Onid_LabelChanged();
            }
        }
        private global::System.String _id_Label;
        partial void Onid_LabelChanging(global::System.String value);
        partial void Onid_LabelChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String a
        {
            get
            {
                return _a;
            }
            set
            {
                OnaChanging(value);
                ReportPropertyChanging("a");
                _a = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("a");
                OnaChanged();
            }
        }
        private global::System.String _a;
        partial void OnaChanging(global::System.String value);
        partial void OnaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String b
        {
            get
            {
                return _b;
            }
            set
            {
                OnbChanging(value);
                ReportPropertyChanging("b");
                _b = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("b");
                OnbChanged();
            }
        }
        private global::System.String _b;
        partial void OnbChanging(global::System.String value);
        partial void OnbChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String c
        {
            get
            {
                return _c;
            }
            set
            {
                OncChanging(value);
                ReportPropertyChanging("c");
                _c = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("c");
                OncChanged();
            }
        }
        private global::System.String _c;
        partial void OncChanging(global::System.String value);
        partial void OncChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id_proyecto
        {
            get
            {
                return _id_proyecto;
            }
            set
            {
                Onid_proyectoChanging(value);
                ReportPropertyChanging("id_proyecto");
                _id_proyecto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("id_proyecto");
                Onid_proyectoChanged();
            }
        }
        private global::System.String _id_proyecto;
        partial void Onid_proyectoChanging(global::System.String value);
        partial void Onid_proyectoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id_asignacion
        {
            get
            {
                return _id_asignacion;
            }
            set
            {
                Onid_asignacionChanging(value);
                ReportPropertyChanging("id_asignacion");
                _id_asignacion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("id_asignacion");
                Onid_asignacionChanged();
            }
        }
        private global::System.String _id_asignacion;
        partial void Onid_asignacionChanging(global::System.String value);
        partial void Onid_asignacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String valor
        {
            get
            {
                return _valor;
            }
            set
            {
                OnvalorChanging(value);
                ReportPropertyChanging("valor");
                _valor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("valor");
                OnvalorChanged();
            }
        }
        private global::System.String _valor;
        partial void OnvalorChanging(global::System.String value);
        partial void OnvalorChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gisiabaseModel1", Name="matriz_alternativa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class matriz_alternativa : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto matriz_alternativa.
        /// </summary>
        /// <param name="id_matrizAlternativa">Valor inicial de la propiedad id_matrizAlternativa.</param>
        /// <param name="id_proyecto">Valor inicial de la propiedad id_proyecto.</param>
        /// <param name="id_experto">Valor inicial de la propiedad id_experto.</param>
        /// <param name="id_criterio">Valor inicial de la propiedad id_criterio.</param>
        public static matriz_alternativa Creatematriz_alternativa(global::System.Int32 id_matrizAlternativa, global::System.Int32 id_proyecto, global::System.Int32 id_experto, global::System.Int32 id_criterio)
        {
            matriz_alternativa matriz_alternativa = new matriz_alternativa();
            matriz_alternativa.id_matrizAlternativa = id_matrizAlternativa;
            matriz_alternativa.id_proyecto = id_proyecto;
            matriz_alternativa.id_experto = id_experto;
            matriz_alternativa.id_criterio = id_criterio;
            return matriz_alternativa;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_matrizAlternativa
        {
            get
            {
                return _id_matrizAlternativa;
            }
            set
            {
                if (_id_matrizAlternativa != value)
                {
                    Onid_matrizAlternativaChanging(value);
                    ReportPropertyChanging("id_matrizAlternativa");
                    _id_matrizAlternativa = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_matrizAlternativa");
                    Onid_matrizAlternativaChanged();
                }
            }
        }
        private global::System.Int32 _id_matrizAlternativa;
        partial void Onid_matrizAlternativaChanging(global::System.Int32 value);
        partial void Onid_matrizAlternativaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_proyecto
        {
            get
            {
                return _id_proyecto;
            }
            set
            {
                Onid_proyectoChanging(value);
                ReportPropertyChanging("id_proyecto");
                _id_proyecto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_proyecto");
                Onid_proyectoChanged();
            }
        }
        private global::System.Int32 _id_proyecto;
        partial void Onid_proyectoChanging(global::System.Int32 value);
        partial void Onid_proyectoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_experto
        {
            get
            {
                return _id_experto;
            }
            set
            {
                Onid_expertoChanging(value);
                ReportPropertyChanging("id_experto");
                _id_experto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_experto");
                Onid_expertoChanged();
            }
        }
        private global::System.Int32 _id_experto;
        partial void Onid_expertoChanging(global::System.Int32 value);
        partial void Onid_expertoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_criterio
        {
            get
            {
                return _id_criterio;
            }
            set
            {
                Onid_criterioChanging(value);
                ReportPropertyChanging("id_criterio");
                _id_criterio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_criterio");
                Onid_criterioChanged();
            }
        }
        private global::System.Int32 _id_criterio;
        partial void Onid_criterioChanging(global::System.Int32 value);
        partial void Onid_criterioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> consistente
        {
            get
            {
                return _consistente;
            }
            set
            {
                OnconsistenteChanging(value);
                ReportPropertyChanging("consistente");
                _consistente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("consistente");
                OnconsistenteChanged();
            }
        }
        private Nullable<global::System.Boolean> _consistente;
        partial void OnconsistenteChanging(Nullable<global::System.Boolean> value);
        partial void OnconsistenteChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gisiabaseModel1", Name="matriz_criterio")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class matriz_criterio : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto matriz_criterio.
        /// </summary>
        /// <param name="id_matrizCriterio">Valor inicial de la propiedad id_matrizCriterio.</param>
        /// <param name="id_proyecto">Valor inicial de la propiedad id_proyecto.</param>
        /// <param name="id_experto">Valor inicial de la propiedad id_experto.</param>
        public static matriz_criterio Creatematriz_criterio(global::System.Int32 id_matrizCriterio, global::System.Int32 id_proyecto, global::System.Int32 id_experto)
        {
            matriz_criterio matriz_criterio = new matriz_criterio();
            matriz_criterio.id_matrizCriterio = id_matrizCriterio;
            matriz_criterio.id_proyecto = id_proyecto;
            matriz_criterio.id_experto = id_experto;
            return matriz_criterio;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_matrizCriterio
        {
            get
            {
                return _id_matrizCriterio;
            }
            set
            {
                if (_id_matrizCriterio != value)
                {
                    Onid_matrizCriterioChanging(value);
                    ReportPropertyChanging("id_matrizCriterio");
                    _id_matrizCriterio = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_matrizCriterio");
                    Onid_matrizCriterioChanged();
                }
            }
        }
        private global::System.Int32 _id_matrizCriterio;
        partial void Onid_matrizCriterioChanging(global::System.Int32 value);
        partial void Onid_matrizCriterioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_proyecto
        {
            get
            {
                return _id_proyecto;
            }
            set
            {
                Onid_proyectoChanging(value);
                ReportPropertyChanging("id_proyecto");
                _id_proyecto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_proyecto");
                Onid_proyectoChanged();
            }
        }
        private global::System.Int32 _id_proyecto;
        partial void Onid_proyectoChanging(global::System.Int32 value);
        partial void Onid_proyectoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_experto
        {
            get
            {
                return _id_experto;
            }
            set
            {
                Onid_expertoChanging(value);
                ReportPropertyChanging("id_experto");
                _id_experto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_experto");
                Onid_expertoChanged();
            }
        }
        private global::System.Int32 _id_experto;
        partial void Onid_expertoChanging(global::System.Int32 value);
        partial void Onid_expertoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> consistente
        {
            get
            {
                return _consistente;
            }
            set
            {
                OnconsistenteChanging(value);
                ReportPropertyChanging("consistente");
                _consistente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("consistente");
                OnconsistenteChanged();
            }
        }
        private Nullable<global::System.Boolean> _consistente;
        partial void OnconsistenteChanging(Nullable<global::System.Boolean> value);
        partial void OnconsistenteChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gisiabaseModel1", Name="proyecto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class proyecto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto proyecto.
        /// </summary>
        /// <param name="id_proyecto">Valor inicial de la propiedad id_proyecto.</param>
        /// <param name="id_creador">Valor inicial de la propiedad id_creador.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="objetivo">Valor inicial de la propiedad objetivo.</param>
        public static proyecto Createproyecto(global::System.Int32 id_proyecto, global::System.Int32 id_creador, global::System.String nombre, global::System.String objetivo)
        {
            proyecto proyecto = new proyecto();
            proyecto.id_proyecto = id_proyecto;
            proyecto.id_creador = id_creador;
            proyecto.nombre = nombre;
            proyecto.objetivo = objetivo;
            return proyecto;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_proyecto
        {
            get
            {
                return _id_proyecto;
            }
            set
            {
                if (_id_proyecto != value)
                {
                    Onid_proyectoChanging(value);
                    ReportPropertyChanging("id_proyecto");
                    _id_proyecto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_proyecto");
                    Onid_proyectoChanged();
                }
            }
        }
        private global::System.Int32 _id_proyecto;
        partial void Onid_proyectoChanging(global::System.Int32 value);
        partial void Onid_proyectoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_creador
        {
            get
            {
                return _id_creador;
            }
            set
            {
                Onid_creadorChanging(value);
                ReportPropertyChanging("id_creador");
                _id_creador = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_creador");
                Onid_creadorChanged();
            }
        }
        private global::System.Int32 _id_creador;
        partial void Onid_creadorChanging(global::System.Int32 value);
        partial void Onid_creadorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String objetivo
        {
            get
            {
                return _objetivo;
            }
            set
            {
                OnobjetivoChanging(value);
                ReportPropertyChanging("objetivo");
                _objetivo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("objetivo");
                OnobjetivoChanged();
            }
        }
        private global::System.String _objetivo;
        partial void OnobjetivoChanging(global::System.String value);
        partial void OnobjetivoChanged();

        #endregion
    
    }

    #endregion
    
}
