//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace sisexperto
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class gisiabaseEntities2 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new gisiabaseEntities2 object using the connection string found in the 'gisiabaseEntities2' section of the application configuration file.
        /// </summary>
        public gisiabaseEntities2() : base("name=gisiabaseEntities2", "gisiabaseEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new gisiabaseEntities2 object.
        /// </summary>
        public gisiabaseEntities2(string connectionString) : base(connectionString, "gisiabaseEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new gisiabaseEntities2 object.
        /// </summary>
        public gisiabaseEntities2(EntityConnection connection) : base(connection, "gisiabaseEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<alternativa> alternativa
        {
            get
            {
                if ((_alternativa == null))
                {
                    _alternativa = base.CreateObjectSet<alternativa>("alternativa");
                }
                return _alternativa;
            }
        }
        private ObjectSet<alternativa> _alternativa;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<comparacion_alternativa> comparacion_alternativa
        {
            get
            {
                if ((_comparacion_alternativa == null))
                {
                    _comparacion_alternativa = base.CreateObjectSet<comparacion_alternativa>("comparacion_alternativa");
                }
                return _comparacion_alternativa;
            }
        }
        private ObjectSet<comparacion_alternativa> _comparacion_alternativa;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<comparacion_criterio> comparacion_criterio
        {
            get
            {
                if ((_comparacion_criterio == null))
                {
                    _comparacion_criterio = base.CreateObjectSet<comparacion_criterio>("comparacion_criterio");
                }
                return _comparacion_criterio;
            }
        }
        private ObjectSet<comparacion_criterio> _comparacion_criterio;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<criterio> criterio
        {
            get
            {
                if ((_criterio == null))
                {
                    _criterio = base.CreateObjectSet<criterio>("criterio");
                }
                return _criterio;
            }
        }
        private ObjectSet<criterio> _criterio;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<experto> experto
        {
            get
            {
                if ((_experto == null))
                {
                    _experto = base.CreateObjectSet<experto>("experto");
                }
                return _experto;
            }
        }
        private ObjectSet<experto> _experto;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<experto_proyecto> experto_proyecto
        {
            get
            {
                if ((_experto_proyecto == null))
                {
                    _experto_proyecto = base.CreateObjectSet<experto_proyecto>("experto_proyecto");
                }
                return _experto_proyecto;
            }
        }
        private ObjectSet<experto_proyecto> _experto_proyecto;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<proyecto> proyecto
        {
            get
            {
                if ((_proyecto == null))
                {
                    _proyecto = base.CreateObjectSet<proyecto>("proyecto");
                }
                return _proyecto;
            }
        }
        private ObjectSet<proyecto> _proyecto;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ILSet> ILSetSet
        {
            get
            {
                if ((_ILSetSet == null))
                {
                    _ILSetSet = base.CreateObjectSet<ILSet>("ILSetSet");
                }
                return _ILSetSet;
            }
        }
        private ObjectSet<ILSet> _ILSetSet;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the alternativa EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToalternativa(alternativa alternativa)
        {
            base.AddObject("alternativa", alternativa);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the comparacion_alternativa EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocomparacion_alternativa(comparacion_alternativa comparacion_alternativa)
        {
            base.AddObject("comparacion_alternativa", comparacion_alternativa);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the comparacion_criterio EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocomparacion_criterio(comparacion_criterio comparacion_criterio)
        {
            base.AddObject("comparacion_criterio", comparacion_criterio);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the criterio EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocriterio(criterio criterio)
        {
            base.AddObject("criterio", criterio);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the experto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToexperto(experto experto)
        {
            base.AddObject("experto", experto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the experto_proyecto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToexperto_proyecto(experto_proyecto experto_proyecto)
        {
            base.AddObject("experto_proyecto", experto_proyecto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the proyecto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToproyecto(proyecto proyecto)
        {
            base.AddObject("proyecto", proyecto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ILSetSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToILSetSet(ILSet iLSet)
        {
            base.AddObject("ILSetSet", iLSet);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gisiabaseModel1", Name="alternativa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class alternativa : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new alternativa object.
        /// </summary>
        /// <param name="id_alternativa">Initial value of the id_alternativa property.</param>
        /// <param name="id_proyecto">Initial value of the id_proyecto property.</param>
        /// <param name="nombre">Initial value of the nombre property.</param>
        public static alternativa Createalternativa(global::System.Int32 id_alternativa, global::System.Int32 id_proyecto, global::System.String nombre)
        {
            alternativa alternativa = new alternativa();
            alternativa.id_alternativa = id_alternativa;
            alternativa.id_proyecto = id_proyecto;
            alternativa.nombre = nombre;
            return alternativa;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_alternativa
        {
            get
            {
                return _id_alternativa;
            }
            set
            {
                if (_id_alternativa != value)
                {
                    Onid_alternativaChanging(value);
                    ReportPropertyChanging("id_alternativa");
                    _id_alternativa = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_alternativa");
                    Onid_alternativaChanged();
                }
            }
        }
        private global::System.Int32 _id_alternativa;
        partial void Onid_alternativaChanging(global::System.Int32 value);
        partial void Onid_alternativaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_proyecto
        {
            get
            {
                return _id_proyecto;
            }
            set
            {
                Onid_proyectoChanging(value);
                ReportPropertyChanging("id_proyecto");
                _id_proyecto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_proyecto");
                Onid_proyectoChanged();
            }
        }
        private global::System.Int32 _id_proyecto;
        partial void Onid_proyectoChanging(global::System.Int32 value);
        partial void Onid_proyectoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gisiabaseModel1", Name="comparacion_alternativa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class comparacion_alternativa : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new comparacion_alternativa object.
        /// </summary>
        /// <param name="id_comparacion">Initial value of the id_comparacion property.</param>
        /// <param name="id_proyecto">Initial value of the id_proyecto property.</param>
        /// <param name="id_experto">Initial value of the id_experto property.</param>
        /// <param name="id_criterio">Initial value of the id_criterio property.</param>
        /// <param name="id_alternativa1">Initial value of the id_alternativa1 property.</param>
        /// <param name="id_alternativa2">Initial value of the id_alternativa2 property.</param>
        /// <param name="pos_fila">Initial value of the pos_fila property.</param>
        /// <param name="pos_columna">Initial value of the pos_columna property.</param>
        public static comparacion_alternativa Createcomparacion_alternativa(global::System.Int32 id_comparacion, global::System.Int32 id_proyecto, global::System.Int32 id_experto, global::System.Int32 id_criterio, global::System.Int32 id_alternativa1, global::System.Int32 id_alternativa2, global::System.Int32 pos_fila, global::System.Int32 pos_columna)
        {
            comparacion_alternativa comparacion_alternativa = new comparacion_alternativa();
            comparacion_alternativa.id_comparacion = id_comparacion;
            comparacion_alternativa.id_proyecto = id_proyecto;
            comparacion_alternativa.id_experto = id_experto;
            comparacion_alternativa.id_criterio = id_criterio;
            comparacion_alternativa.id_alternativa1 = id_alternativa1;
            comparacion_alternativa.id_alternativa2 = id_alternativa2;
            comparacion_alternativa.pos_fila = pos_fila;
            comparacion_alternativa.pos_columna = pos_columna;
            return comparacion_alternativa;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_comparacion
        {
            get
            {
                return _id_comparacion;
            }
            set
            {
                if (_id_comparacion != value)
                {
                    Onid_comparacionChanging(value);
                    ReportPropertyChanging("id_comparacion");
                    _id_comparacion = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_comparacion");
                    Onid_comparacionChanged();
                }
            }
        }
        private global::System.Int32 _id_comparacion;
        partial void Onid_comparacionChanging(global::System.Int32 value);
        partial void Onid_comparacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_proyecto
        {
            get
            {
                return _id_proyecto;
            }
            set
            {
                Onid_proyectoChanging(value);
                ReportPropertyChanging("id_proyecto");
                _id_proyecto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_proyecto");
                Onid_proyectoChanged();
            }
        }
        private global::System.Int32 _id_proyecto;
        partial void Onid_proyectoChanging(global::System.Int32 value);
        partial void Onid_proyectoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_experto
        {
            get
            {
                return _id_experto;
            }
            set
            {
                Onid_expertoChanging(value);
                ReportPropertyChanging("id_experto");
                _id_experto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_experto");
                Onid_expertoChanged();
            }
        }
        private global::System.Int32 _id_experto;
        partial void Onid_expertoChanging(global::System.Int32 value);
        partial void Onid_expertoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_criterio
        {
            get
            {
                return _id_criterio;
            }
            set
            {
                Onid_criterioChanging(value);
                ReportPropertyChanging("id_criterio");
                _id_criterio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_criterio");
                Onid_criterioChanged();
            }
        }
        private global::System.Int32 _id_criterio;
        partial void Onid_criterioChanging(global::System.Int32 value);
        partial void Onid_criterioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_alternativa1
        {
            get
            {
                return _id_alternativa1;
            }
            set
            {
                Onid_alternativa1Changing(value);
                ReportPropertyChanging("id_alternativa1");
                _id_alternativa1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_alternativa1");
                Onid_alternativa1Changed();
            }
        }
        private global::System.Int32 _id_alternativa1;
        partial void Onid_alternativa1Changing(global::System.Int32 value);
        partial void Onid_alternativa1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_alternativa2
        {
            get
            {
                return _id_alternativa2;
            }
            set
            {
                Onid_alternativa2Changing(value);
                ReportPropertyChanging("id_alternativa2");
                _id_alternativa2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_alternativa2");
                Onid_alternativa2Changed();
            }
        }
        private global::System.Int32 _id_alternativa2;
        partial void Onid_alternativa2Changing(global::System.Int32 value);
        partial void Onid_alternativa2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pos_fila
        {
            get
            {
                return _pos_fila;
            }
            set
            {
                Onpos_filaChanging(value);
                ReportPropertyChanging("pos_fila");
                _pos_fila = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pos_fila");
                Onpos_filaChanged();
            }
        }
        private global::System.Int32 _pos_fila;
        partial void Onpos_filaChanging(global::System.Int32 value);
        partial void Onpos_filaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pos_columna
        {
            get
            {
                return _pos_columna;
            }
            set
            {
                Onpos_columnaChanging(value);
                ReportPropertyChanging("pos_columna");
                _pos_columna = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pos_columna");
                Onpos_columnaChanged();
            }
        }
        private global::System.Int32 _pos_columna;
        partial void Onpos_columnaChanging(global::System.Int32 value);
        partial void Onpos_columnaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> valor
        {
            get
            {
                return _valor;
            }
            set
            {
                OnvalorChanging(value);
                ReportPropertyChanging("valor");
                _valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("valor");
                OnvalorChanged();
            }
        }
        private Nullable<global::System.Double> _valor;
        partial void OnvalorChanging(Nullable<global::System.Double> value);
        partial void OnvalorChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gisiabaseModel1", Name="comparacion_criterio")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class comparacion_criterio : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new comparacion_criterio object.
        /// </summary>
        /// <param name="id_comparacion">Initial value of the id_comparacion property.</param>
        /// <param name="id_proyecto">Initial value of the id_proyecto property.</param>
        /// <param name="id_experto">Initial value of the id_experto property.</param>
        /// <param name="id_criterio1">Initial value of the id_criterio1 property.</param>
        /// <param name="id_criterio2">Initial value of the id_criterio2 property.</param>
        /// <param name="pos_fila">Initial value of the pos_fila property.</param>
        /// <param name="pos_columna">Initial value of the pos_columna property.</param>
        public static comparacion_criterio Createcomparacion_criterio(global::System.Int32 id_comparacion, global::System.Int32 id_proyecto, global::System.Int32 id_experto, global::System.Int32 id_criterio1, global::System.Int32 id_criterio2, global::System.Int32 pos_fila, global::System.Int32 pos_columna)
        {
            comparacion_criterio comparacion_criterio = new comparacion_criterio();
            comparacion_criterio.id_comparacion = id_comparacion;
            comparacion_criterio.id_proyecto = id_proyecto;
            comparacion_criterio.id_experto = id_experto;
            comparacion_criterio.id_criterio1 = id_criterio1;
            comparacion_criterio.id_criterio2 = id_criterio2;
            comparacion_criterio.pos_fila = pos_fila;
            comparacion_criterio.pos_columna = pos_columna;
            return comparacion_criterio;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_comparacion
        {
            get
            {
                return _id_comparacion;
            }
            set
            {
                if (_id_comparacion != value)
                {
                    Onid_comparacionChanging(value);
                    ReportPropertyChanging("id_comparacion");
                    _id_comparacion = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_comparacion");
                    Onid_comparacionChanged();
                }
            }
        }
        private global::System.Int32 _id_comparacion;
        partial void Onid_comparacionChanging(global::System.Int32 value);
        partial void Onid_comparacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_proyecto
        {
            get
            {
                return _id_proyecto;
            }
            set
            {
                Onid_proyectoChanging(value);
                ReportPropertyChanging("id_proyecto");
                _id_proyecto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_proyecto");
                Onid_proyectoChanged();
            }
        }
        private global::System.Int32 _id_proyecto;
        partial void Onid_proyectoChanging(global::System.Int32 value);
        partial void Onid_proyectoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_experto
        {
            get
            {
                return _id_experto;
            }
            set
            {
                Onid_expertoChanging(value);
                ReportPropertyChanging("id_experto");
                _id_experto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_experto");
                Onid_expertoChanged();
            }
        }
        private global::System.Int32 _id_experto;
        partial void Onid_expertoChanging(global::System.Int32 value);
        partial void Onid_expertoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_criterio1
        {
            get
            {
                return _id_criterio1;
            }
            set
            {
                Onid_criterio1Changing(value);
                ReportPropertyChanging("id_criterio1");
                _id_criterio1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_criterio1");
                Onid_criterio1Changed();
            }
        }
        private global::System.Int32 _id_criterio1;
        partial void Onid_criterio1Changing(global::System.Int32 value);
        partial void Onid_criterio1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_criterio2
        {
            get
            {
                return _id_criterio2;
            }
            set
            {
                Onid_criterio2Changing(value);
                ReportPropertyChanging("id_criterio2");
                _id_criterio2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_criterio2");
                Onid_criterio2Changed();
            }
        }
        private global::System.Int32 _id_criterio2;
        partial void Onid_criterio2Changing(global::System.Int32 value);
        partial void Onid_criterio2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pos_fila
        {
            get
            {
                return _pos_fila;
            }
            set
            {
                Onpos_filaChanging(value);
                ReportPropertyChanging("pos_fila");
                _pos_fila = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pos_fila");
                Onpos_filaChanged();
            }
        }
        private global::System.Int32 _pos_fila;
        partial void Onpos_filaChanging(global::System.Int32 value);
        partial void Onpos_filaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pos_columna
        {
            get
            {
                return _pos_columna;
            }
            set
            {
                Onpos_columnaChanging(value);
                ReportPropertyChanging("pos_columna");
                _pos_columna = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pos_columna");
                Onpos_columnaChanged();
            }
        }
        private global::System.Int32 _pos_columna;
        partial void Onpos_columnaChanging(global::System.Int32 value);
        partial void Onpos_columnaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> valor
        {
            get
            {
                return _valor;
            }
            set
            {
                OnvalorChanging(value);
                ReportPropertyChanging("valor");
                _valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("valor");
                OnvalorChanged();
            }
        }
        private Nullable<global::System.Double> _valor;
        partial void OnvalorChanging(Nullable<global::System.Double> value);
        partial void OnvalorChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gisiabaseModel1", Name="criterio")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class criterio : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new criterio object.
        /// </summary>
        /// <param name="id_criterio">Initial value of the id_criterio property.</param>
        /// <param name="id_proyecto">Initial value of the id_proyecto property.</param>
        /// <param name="nombre">Initial value of the nombre property.</param>
        /// <param name="iLPonderacion">Initial value of the ILPonderacion property.</param>
        public static criterio Createcriterio(global::System.Int32 id_criterio, global::System.Int32 id_proyecto, global::System.String nombre, global::System.Double iLPonderacion)
        {
            criterio criterio = new criterio();
            criterio.id_criterio = id_criterio;
            criterio.id_proyecto = id_proyecto;
            criterio.nombre = nombre;
            criterio.ILPonderacion = iLPonderacion;
            return criterio;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_criterio
        {
            get
            {
                return _id_criterio;
            }
            set
            {
                if (_id_criterio != value)
                {
                    Onid_criterioChanging(value);
                    ReportPropertyChanging("id_criterio");
                    _id_criterio = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_criterio");
                    Onid_criterioChanged();
                }
            }
        }
        private global::System.Int32 _id_criterio;
        partial void Onid_criterioChanging(global::System.Int32 value);
        partial void Onid_criterioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_proyecto
        {
            get
            {
                return _id_proyecto;
            }
            set
            {
                Onid_proyectoChanging(value);
                ReportPropertyChanging("id_proyecto");
                _id_proyecto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_proyecto");
                Onid_proyectoChanged();
            }
        }
        private global::System.Int32 _id_proyecto;
        partial void Onid_proyectoChanging(global::System.Int32 value);
        partial void Onid_proyectoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double ILPonderacion
        {
            get
            {
                return _ILPonderacion;
            }
            set
            {
                OnILPonderacionChanging(value);
                ReportPropertyChanging("ILPonderacion");
                _ILPonderacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ILPonderacion");
                OnILPonderacionChanged();
            }
        }
        private global::System.Double _ILPonderacion;
        partial void OnILPonderacionChanging(global::System.Double value);
        partial void OnILPonderacionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gisiabaseModel1", Name="experto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class experto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new experto object.
        /// </summary>
        /// <param name="id_experto">Initial value of the id_experto property.</param>
        /// <param name="nombre">Initial value of the nombre property.</param>
        /// <param name="apellido">Initial value of the apellido property.</param>
        /// <param name="nom_usuario">Initial value of the nom_usuario property.</param>
        /// <param name="clave">Initial value of the clave property.</param>
        public static experto Createexperto(global::System.Int32 id_experto, global::System.String nombre, global::System.String apellido, global::System.String nom_usuario, global::System.String clave)
        {
            experto experto = new experto();
            experto.id_experto = id_experto;
            experto.nombre = nombre;
            experto.apellido = apellido;
            experto.nom_usuario = nom_usuario;
            experto.clave = clave;
            return experto;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_experto
        {
            get
            {
                return _id_experto;
            }
            set
            {
                if (_id_experto != value)
                {
                    Onid_expertoChanging(value);
                    ReportPropertyChanging("id_experto");
                    _id_experto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_experto");
                    Onid_expertoChanged();
                }
            }
        }
        private global::System.Int32 _id_experto;
        partial void Onid_expertoChanging(global::System.Int32 value);
        partial void Onid_expertoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String apellido
        {
            get
            {
                return _apellido;
            }
            set
            {
                OnapellidoChanging(value);
                ReportPropertyChanging("apellido");
                _apellido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("apellido");
                OnapellidoChanged();
            }
        }
        private global::System.String _apellido;
        partial void OnapellidoChanging(global::System.String value);
        partial void OnapellidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nom_usuario
        {
            get
            {
                return _nom_usuario;
            }
            set
            {
                Onnom_usuarioChanging(value);
                ReportPropertyChanging("nom_usuario");
                _nom_usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nom_usuario");
                Onnom_usuarioChanged();
            }
        }
        private global::System.String _nom_usuario;
        partial void Onnom_usuarioChanging(global::System.String value);
        partial void Onnom_usuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String clave
        {
            get
            {
                return _clave;
            }
            set
            {
                OnclaveChanging(value);
                ReportPropertyChanging("clave");
                _clave = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("clave");
                OnclaveChanged();
            }
        }
        private global::System.String _clave;
        partial void OnclaveChanging(global::System.String value);
        partial void OnclaveChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gisiabaseModel1", Name="experto_proyecto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class experto_proyecto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new experto_proyecto object.
        /// </summary>
		/// <param name="id_asignacion">Valor inicial de la propiedad id_asignacion.</param>
        /// <param name="id_proyecto">Valor inicial de la propiedad id_proyecto.</param>
        /// <param name="id_experto">Valor inicial de la propiedad id_experto.</param>
        /// <param name="iLPonderacion">Valor inicial de la propiedad ILPonderacion.</param>
        /// <param name="valoracion_consistente">Valor inicial de la propiedad valoracion_consistente.</param>
        public static experto_proyecto Createexperto_proyecto(global::System.Int32 id_asignacion, global::System.Int32 id_proyecto, global::System.Int32 id_experto, global::System.Double iLPonderacion, global::System.Boolean valoracion_consistente)

        {
            experto_proyecto experto_proyecto = new experto_proyecto();
            experto_proyecto.id_asignacion = id_asignacion;
            experto_proyecto.id_proyecto = id_proyecto;
            experto_proyecto.id_experto = id_experto;
            experto_proyecto.ILPonderacion = iLPonderacion;
            experto_proyecto.valoracion_consistente = valoracion_consistente;
            return experto_proyecto;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_asignacion
        {
            get
            {
                return _id_asignacion;
            }
            set
            {
                if (_id_asignacion != value)
                {
                    Onid_asignacionChanging(value);
                    ReportPropertyChanging("id_asignacion");
                    _id_asignacion = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_asignacion");
                    Onid_asignacionChanged();
                }
            }
        }
        private global::System.Int32 _id_asignacion;
        partial void Onid_asignacionChanging(global::System.Int32 value);
        partial void Onid_asignacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_proyecto
        {
            get
            {
                return _id_proyecto;
            }
            set
            {
                Onid_proyectoChanging(value);
                ReportPropertyChanging("id_proyecto");
                _id_proyecto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_proyecto");
                Onid_proyectoChanged();
            }
        }
        private global::System.Int32 _id_proyecto;
        partial void Onid_proyectoChanging(global::System.Int32 value);
        partial void Onid_proyectoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_experto
        {
            get
            {
                return _id_experto;
            }
            set
            {
                Onid_expertoChanging(value);
                ReportPropertyChanging("id_experto");
                _id_experto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_experto");
                Onid_expertoChanged();
            }
        }
        private global::System.Int32 _id_experto;
        partial void Onid_expertoChanging(global::System.Int32 value);
        partial void Onid_expertoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> ponderacion
        {
            get
            {
                return _ponderacion;
            }
            set
            {
                OnponderacionChanging(value);
                ReportPropertyChanging("ponderacion");
                _ponderacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ponderacion");
                OnponderacionChanged();
            }
        }
        private Nullable<global::System.Double> _ponderacion;
        partial void OnponderacionChanging(Nullable<global::System.Double> value);
        partial void OnponderacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double ILPonderacion
        {
            get
            {
                return _ILPonderacion;
            }
            set
            {
                OnILPonderacionChanging(value);
                ReportPropertyChanging("ILPonderacion");
                _ILPonderacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ILPonderacion");
                OnILPonderacionChanged();
            }
        }
        private global::System.Double _ILPonderacion;
        partial void OnILPonderacionChanging(global::System.Double value);
        partial void OnILPonderacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean valoracion_consistente
        {
            get
            {
                return _valoracion_consistente;
            }
            set
            {
                Onvaloracion_consistenteChanging(value);
                ReportPropertyChanging("valoracion_consistente");
                _valoracion_consistente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("valoracion_consistente");
                Onvaloracion_consistenteChanged();
            }
        }
        private global::System.Boolean _valoracion_consistente;
        partial void Onvaloracion_consistenteChanging(global::System.Boolean value);
        partial void Onvaloracion_consistenteChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gisiabaseModel1", Name="ILSet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ILSet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ILSet object.
        /// </summary>
        /// <param name="id_Model">Initial value of the id_Model property.</param>
        /// <param name="id_Label">Initial value of the id_Label property.</param>
        /// <param name="nombre">Initial value of the nombre property.</param>
        /// <param name="a">Initial value of the a property.</param>
        /// <param name="b">Initial value of the b property.</param>
        /// <param name="c">Initial value of the c property.</param>
        /// <param name="id_proyecto">Initial value of the id_proyecto property.</param>
        /// <param name="id_asignacion">Initial value of the id_asignacion property.</param>
        /// <param name="valor">Initial value of the valor property.</param>
        public static ILSet CreateILSet(global::System.Int32 id_Model, global::System.String id_Label, global::System.String nombre, global::System.String a, global::System.String b, global::System.String c, global::System.String id_proyecto, global::System.String id_asignacion, global::System.String valor)
        {
            ILSet iLSet = new ILSet();
            iLSet.id_Model = id_Model;
            iLSet.id_Label = id_Label;
            iLSet.nombre = nombre;
            iLSet.a = a;
            iLSet.b = b;
            iLSet.c = c;
            iLSet.id_proyecto = id_proyecto;
            iLSet.id_asignacion = id_asignacion;
            iLSet.valor = valor;
            return iLSet;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Model
        {
            get
            {
                return _id_Model;
            }
            set
            {
                if (_id_Model != value)
                {
                    Onid_ModelChanging(value);
                    ReportPropertyChanging("id_Model");
                    _id_Model = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_Model");
                    Onid_ModelChanged();
                }
            }
        }
        private global::System.Int32 _id_Model;
        partial void Onid_ModelChanging(global::System.Int32 value);
        partial void Onid_ModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id_Label
        {
            get
            {
                return _id_Label;
            }
            set
            {
                Onid_LabelChanging(value);
                ReportPropertyChanging("id_Label");
                _id_Label = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("id_Label");
                Onid_LabelChanged();
            }
        }
        private global::System.String _id_Label;
        partial void Onid_LabelChanging(global::System.String value);
        partial void Onid_LabelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String a
        {
            get
            {
                return _a;
            }
            set
            {
                OnaChanging(value);
                ReportPropertyChanging("a");
                _a = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("a");
                OnaChanged();
            }
        }
        private global::System.String _a;
        partial void OnaChanging(global::System.String value);
        partial void OnaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String b
        {
            get
            {
                return _b;
            }
            set
            {
                OnbChanging(value);
                ReportPropertyChanging("b");
                _b = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("b");
                OnbChanged();
            }
        }
        private global::System.String _b;
        partial void OnbChanging(global::System.String value);
        partial void OnbChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String c
        {
            get
            {
                return _c;
            }
            set
            {
                OncChanging(value);
                ReportPropertyChanging("c");
                _c = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("c");
                OncChanged();
            }
        }
        private global::System.String _c;
        partial void OncChanging(global::System.String value);
        partial void OncChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id_proyecto
        {
            get
            {
                return _id_proyecto;
            }
            set
            {
                Onid_proyectoChanging(value);
                ReportPropertyChanging("id_proyecto");
                _id_proyecto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("id_proyecto");
                Onid_proyectoChanged();
            }
        }
        private global::System.String _id_proyecto;
        partial void Onid_proyectoChanging(global::System.String value);
        partial void Onid_proyectoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id_asignacion
        {
            get
            {
                return _id_asignacion;
            }
            set
            {
                Onid_asignacionChanging(value);
                ReportPropertyChanging("id_asignacion");
                _id_asignacion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("id_asignacion");
                Onid_asignacionChanged();
            }
        }
        private global::System.String _id_asignacion;
        partial void Onid_asignacionChanging(global::System.String value);
        partial void Onid_asignacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String valor
        {
            get
            {
                return _valor;
            }
            set
            {
                OnvalorChanging(value);
                ReportPropertyChanging("valor");
                _valor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("valor");
                OnvalorChanged();
            }
        }
        private global::System.String _valor;
        partial void OnvalorChanging(global::System.String value);
        partial void OnvalorChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gisiabaseModel1", Name="proyecto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class proyecto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new proyecto object.
        /// </summary>
        /// <param name="id_proyecto">Initial value of the id_proyecto property.</param>
        /// <param name="id_creador">Initial value of the id_creador property.</param>
        /// <param name="nombre">Initial value of the nombre property.</param>
        /// <param name="objetivo">Initial value of the objetivo property.</param>
        public static proyecto Createproyecto(global::System.Int32 id_proyecto, global::System.Int32 id_creador, global::System.String nombre, global::System.String objetivo)
        {
            proyecto proyecto = new proyecto();
            proyecto.id_proyecto = id_proyecto;
            proyecto.id_creador = id_creador;
            proyecto.nombre = nombre;
            proyecto.objetivo = objetivo;
            return proyecto;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_proyecto
        {
            get
            {
                return _id_proyecto;
            }
            set
            {
                if (_id_proyecto != value)
                {
                    Onid_proyectoChanging(value);
                    ReportPropertyChanging("id_proyecto");
                    _id_proyecto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_proyecto");
                    Onid_proyectoChanged();
                }
            }
        }
        private global::System.Int32 _id_proyecto;
        partial void Onid_proyectoChanging(global::System.Int32 value);
        partial void Onid_proyectoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_creador
        {
            get
            {
                return _id_creador;
            }
            set
            {
                Onid_creadorChanging(value);
                ReportPropertyChanging("id_creador");
                _id_creador = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_creador");
                Onid_creadorChanged();
            }
        }
        private global::System.Int32 _id_creador;
        partial void Onid_creadorChanging(global::System.Int32 value);
        partial void Onid_creadorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String objetivo
        {
            get
            {
                return _objetivo;
            }
            set
            {
                OnobjetivoChanging(value);
                ReportPropertyChanging("objetivo");
                _objetivo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("objetivo");
                OnobjetivoChanged();
            }
        }
        private global::System.String _objetivo;
        partial void OnobjetivoChanging(global::System.String value);
        partial void OnobjetivoChanged();

        #endregion

    
    }

    #endregion

    
}
