// <auto-generated />
namespace sisExperto.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class claseExpertosEnProyectoagregada : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(claseExpertosEnProyectoagregada));
        
        string IMigrationMetadata.Id
        {
            get { return "201211030107485_clase ExpertosEnProyecto agregada"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
