// <auto-generated />
namespace sisExperto.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class cambiosEEP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cambiosEEP));
        
        string IMigrationMetadata.Id
        {
            get { return "201211062241515_cambiosEEP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
