// <auto-generated />
namespace sisExperto.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class cambiodenombredeunatablaVCPE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cambiodenombredeunatablaVCPE));
        
        string IMigrationMetadata.Id
        {
            get { return "201211030049545_cambio de nombre de una tabla VCPE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
