// <auto-generated />
namespace sisexperto.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Nuevo3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nuevo3));
        
        string IMigrationMetadata.Id
        {
            get { return "201211220358501_Nuevo3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
