// <auto-generated />
namespace sisexperto.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class GisiaExpertoContextcreador : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GisiaExpertoContextcreador));
        
        string IMigrationMetadata.Id
        {
            get { return "201211030047193_GisiaExpertoContext creador"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
