// <auto-generated />
namespace sisexperto.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Nuevo1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nuevo1));
        
        string IMigrationMetadata.Id
        {
            get { return "201211220342040_Nuevo1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
