// <auto-generated />
namespace sisexperto.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class cero : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cero));
        
        string IMigrationMetadata.Id
        {
            get { return "201211161430491_cero"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
