// <auto-generated />
namespace sisExperto.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class administradores : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(administradores));
        
        string IMigrationMetadata.Id
        {
            get { return "201211052357258_administradores"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
